### ISSUE TITLE
Game crashes with no error message on GOG_Friends_GetPersonaName()

### ISSUE THREAD

**Issue by Retrific** [YoYoGames/GMEXT-GOG#12] opened 2024-10-13 21:07 UTC
I am using LTS and the latest release [GOG Ext v1.4.0](https://github.com/YoYoGames/GMEXT-GOG/releases/tag/1.4.0) but as soon as I use GOG_Friends_GetPersonaName() it seems to crash with no error message. Just closes.

I made sure to have GOG_User_SignInGalaxy(), GOG_ProcessData(), GOG_Friends_RequestUserInformation() and GOG_Stats_RequestUserStatsAndAchievements() all complete successfully first.

If I do GOG_Friends_GetFriendPersonaName(GOG_User_GetGalaxyID()) instead of GOG_Friends_GetPersonaName() it works fine.
But then it crashes as soon as I use GOG_Stats_GetAchievement - So there must be something more deeply wrong with what I do and not just with that one function.

Any idea?

**Comment by DiasFranciscoA** [comment] 2024-10-22 16:33
Hello @Retrific, thank you for reaching out to us.
We have recently released version 2.0.0 of the extension with numerous bug fixes, and it also requires the latest SDK.
This bug should be fixed now (as we couldn't reproduce it on our end). I'll close the ticket as done.

If the issue persists, please do open another ticket and provide a demo project with the crash.

**Closed by DiasFranciscoA** 2024-10-22 16:33 UTC
